# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFirstDrawing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'StantDrawing',        git: 'https://github.com/stantmob/stant-drawing.git',           branch: 'master'

  # Pods for MyFirstDrawing

end
